import { Inter } from 'next/font/google';
import type { ReactNode } from 'react';

import './globals.css';
import SearchInput from '@/components/SearchInput';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
  modal: ReactNode;
};

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang="en">
      <body className={cn('max-w-screen-xl mx-auto md:p-6', inter.className)}>
        <SearchInput />
        {children}
        {modal}
      </body>
    </html>
  );
}
